using System.Windows.Controls;

namespace PCConfigurator.View.ComponentsUserControls;

/// <summary>
/// Interaction logic for GpuUserControl.xaml
/// </summary>
public partial class GpuUserControl : UserControl
{
    public GpuUserControl()
    {
        InitializeComponent();
        dataGrid.AutoGeneratedColumns += SizeGrid;
    }

    private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        if (e.PropertyName == "GpuId")
            e.Cancel = true;

        else if (e.PropertyName == "Configurations")
            e.Cancel = true;

        else if (e.PropertyName == "Model")
            e.Column.Header = "Модель";

        else if (e.PropertyName == "CoreClock")
            e.Column.Header = "Частота";

        else if (e.PropertyName == "BoostClock")
            e.Column.Header = "Турбочастота";

        else if (e.PropertyName == "VramCapacity")
            e.Column.Header = "Объем видеопамяти";

        else if (e.PropertyName == "PowerConsumption")
            e.Column.Header = "Энергопотребление";
    }

    public void SizeGrid(object? sender, EventArgs e)
    {
        foreach (var column in dataGrid.Columns)
        {
            if ((string)column.Header == "Модель")
            {
                column.Width = new DataGridLength(1.0, DataGridLengthUnitType.Auto);
            }
        }
    }
}
