using PCConfigurator.Converters;
using System.Windows.Controls;
using System.Windows.Data;

namespace PCConfigurator.View.ComponentsUserControls;

/// <summary>
/// Interaction logic for MotherboardUserControl.xaml
/// </summary>
public partial class MotherboardUserControl : UserControl
{
    public MotherboardUserControl()
    {
        InitializeComponent();
        dataGrid.AutoGeneratedColumns += SizeGrid;
    }

    private void DataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
    {
        if (e.PropertyName == "MotherboardId")
            e.Cancel = true;

        else if (e.PropertyName == "Configurations")
            e.Cancel = true;

        else if (e.PropertyName == "SocketId")
            e.Cancel = true;

        else if (e.PropertyName == "ChipsetId")
            e.Cancel = true;

        else if (e.PropertyName == "M2Slots")
        {
            e.Column.Header = "Разъёмы M.2";
            if (e.Column is DataGridTextColumn textColumn)
            {
                if (textColumn.Binding is Binding binding)
                {
                    binding.Converter = new M2SlotsConverter();
                }
            }
        }

        else if (e.PropertyName == "Model")
            e.Column.Header = "Модель";

        else if (e.PropertyName == "Socket")
            e.Column.Header = "Сокет";

        else if (e.PropertyName == "Chipset")
            e.Column.Header = "Чипсет";

        else if (e.PropertyName == "RamType")
            e.Column.Header = "Тип памяти";

        else if (e.PropertyName == "RamSlots")
            e.Column.Header = "Слоты памяти";

        else if (e.PropertyName == "MaxRamCapacity")
            e.Column.Header = "Максимальный объём памяти";

        else if (e.PropertyName == "Sata3Ports")
            e.Column.Header = "Коннекторы SATA";

        else if (e.PropertyName == "PCIex16Slots")
            e.Column.Header = "Слоты PCIex16";
    }

    public void SizeGrid(object? sender, EventArgs e)
    {
        foreach (var column in dataGrid.Columns)
        {
            if ((string)column.Header == "Модель")
            {
                column.Width = new DataGridLength(1.0, DataGridLengthUnitType.Auto);
            }

            else if ((string)column.Header == "Разъёмы M.2")
            {
                column.Width = new DataGridLength(1.0, DataGridLengthUnitType.Auto);
            }
        }
    }
}
