### YamlMime:ManagedReference
items:
- uid: PCConfigurator.Helper.ConfigurationIE
  commentId: T:PCConfigurator.Helper.ConfigurationIE
  id: ConfigurationIE
  parent: PCConfigurator.Helper
  children:
  - PCConfigurator.Helper.ConfigurationIE.Export(System.String,PCConfigurator.Model.Components.Configuration)
  - PCConfigurator.Helper.ConfigurationIE.Import(System.String,PCConfigurator.Model.ApplicationContext)
  langs:
  - csharp
  - vb
  name: ConfigurationIE
  nameWithType: ConfigurationIE
  fullName: PCConfigurator.Helper.ConfigurationIE
  type: Class
  source:
    remote:
      path: PCConfigurator/Helper/ConfigurationIE.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: ConfigurationIE
    path: ../PCConfigurator/Helper/ConfigurationIE.cs
    startLine: 36
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Helper
  remarks: Подробное руководство [Руководство 1](../guides/guide1.html)
  example: []
  syntax:
    content: public static class ConfigurationIE
    content.vb: Public Module ConfigurationIE
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: PCConfigurator.Helper.ConfigurationIE.Export(System.String,PCConfigurator.Model.Components.Configuration)
  commentId: M:PCConfigurator.Helper.ConfigurationIE.Export(System.String,PCConfigurator.Model.Components.Configuration)
  id: Export(System.String,PCConfigurator.Model.Components.Configuration)
  parent: PCConfigurator.Helper.ConfigurationIE
  langs:
  - csharp
  - vb
  name: Export(string, Configuration)
  nameWithType: ConfigurationIE.Export(string, Configuration)
  fullName: PCConfigurator.Helper.ConfigurationIE.Export(string, PCConfigurator.Model.Components.Configuration)
  type: Method
  source:
    remote:
      path: PCConfigurator/Helper/ConfigurationIE.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: Export
    path: ../PCConfigurator/Helper/ConfigurationIE.cs
    startLine: 212
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Helper
  summary: Export pc configuration to a file. If file does not exist creates it.
  example:
  - >-
    Usage example:

    <pre><code class="lang-csharp">var configuration = new Configuration();

    // Add components to a configuration here

    var path = "conf.json";

    if (ConfigurationIE.Export(path, configuration))
        Console.WriteLine($"Configuration {configuration.Name} exported successfuly.");
    else
        Console.WriteLine($"Error while exporting configuration {configuration.Name}.");</code></pre>
  syntax:
    content: public static bool Export(string path, Configuration configuration)
    parameters:
    - id: path
      type: System.String
      description: Path to file to export in.
    - id: configuration
      type: PCConfigurator.Model.Components.Configuration
      description: Configuration to export.
    return:
      type: System.Boolean
      description: True if succesfull, False if configuration is not compatible.
    content.vb: Public Shared Function Export(path As String, configuration As Configuration) As Boolean
  overload: PCConfigurator.Helper.ConfigurationIE.Export*
  nameWithType.vb: ConfigurationIE.Export(String, Configuration)
  fullName.vb: PCConfigurator.Helper.ConfigurationIE.Export(String, PCConfigurator.Model.Components.Configuration)
  name.vb: Export(String, Configuration)
- uid: PCConfigurator.Helper.ConfigurationIE.Import(System.String,PCConfigurator.Model.ApplicationContext)
  commentId: M:PCConfigurator.Helper.ConfigurationIE.Import(System.String,PCConfigurator.Model.ApplicationContext)
  id: Import(System.String,PCConfigurator.Model.ApplicationContext)
  parent: PCConfigurator.Helper.ConfigurationIE
  langs:
  - csharp
  - vb
  name: Import(string, ApplicationContext)
  nameWithType: ConfigurationIE.Import(string, ApplicationContext)
  fullName: PCConfigurator.Helper.ConfigurationIE.Import(string, PCConfigurator.Model.ApplicationContext)
  type: Method
  source:
    remote:
      path: PCConfigurator/Helper/ConfigurationIE.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: Import
    path: ../PCConfigurator/Helper/ConfigurationIE.cs
    startLine: 382
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Helper
  summary: Imports pc configuration from file.
  example: []
  syntax:
    content: public static Configuration? Import(string path, ApplicationContext dbContext)
    parameters:
    - id: path
      type: System.String
      description: Path to a file
    - id: dbContext
      type: PCConfigurator.Model.ApplicationContext
      description: Database context to use for constraction of configuration
    return:
      type: PCConfigurator.Model.Components.Configuration
      description: Imported configuration
    content.vb: Public Shared Function Import(path As String, dbContext As ApplicationContext) As Configuration
  overload: PCConfigurator.Helper.ConfigurationIE.Import*
  nameWithType.vb: ConfigurationIE.Import(String, ApplicationContext)
  fullName.vb: PCConfigurator.Helper.ConfigurationIE.Import(String, PCConfigurator.Model.ApplicationContext)
  name.vb: Import(String, ApplicationContext)
references:
- uid: PCConfigurator.Helper
  commentId: N:PCConfigurator.Helper
  href: PCConfigurator.html
  name: PCConfigurator.Helper
  nameWithType: PCConfigurator.Helper
  fullName: PCConfigurator.Helper
  spec.csharp:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Helper
    name: Helper
    href: PCConfigurator.Helper.html
  spec.vb:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Helper
    name: Helper
    href: PCConfigurator.Helper.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: PCConfigurator.Helper.ConfigurationIE.Export*
  commentId: Overload:PCConfigurator.Helper.ConfigurationIE.Export
  href: PCConfigurator.Helper.ConfigurationIE.html#PCConfigurator_Helper_ConfigurationIE_Export_System_String_PCConfigurator_Model_Components_Configuration_
  name: Export
  nameWithType: ConfigurationIE.Export
  fullName: PCConfigurator.Helper.ConfigurationIE.Export
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: PCConfigurator.Model.Components.Configuration
  commentId: T:PCConfigurator.Model.Components.Configuration
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Configuration.html
  name: Configuration
  nameWithType: Configuration
  fullName: PCConfigurator.Model.Components.Configuration
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: PCConfigurator.Model.Components
  commentId: N:PCConfigurator.Model.Components
  href: PCConfigurator.html
  name: PCConfigurator.Model.Components
  nameWithType: PCConfigurator.Model.Components
  fullName: PCConfigurator.Model.Components
  spec.csharp:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
  - name: .
  - uid: PCConfigurator.Model.Components
    name: Components
    href: PCConfigurator.Model.Components.html
  spec.vb:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
  - name: .
  - uid: PCConfigurator.Model.Components
    name: Components
    href: PCConfigurator.Model.Components.html
- uid: PCConfigurator.Helper.ConfigurationIE.Import*
  commentId: Overload:PCConfigurator.Helper.ConfigurationIE.Import
  href: PCConfigurator.Helper.ConfigurationIE.html#PCConfigurator_Helper_ConfigurationIE_Import_System_String_PCConfigurator_Model_ApplicationContext_
  name: Import
  nameWithType: ConfigurationIE.Import
  fullName: PCConfigurator.Helper.ConfigurationIE.Import
- uid: PCConfigurator.Model.ApplicationContext
  commentId: T:PCConfigurator.Model.ApplicationContext
  parent: PCConfigurator.Model
  href: PCConfigurator.Model.ApplicationContext.html
  name: ApplicationContext
  nameWithType: ApplicationContext
  fullName: PCConfigurator.Model.ApplicationContext
- uid: PCConfigurator.Model
  commentId: N:PCConfigurator.Model
  href: PCConfigurator.html
  name: PCConfigurator.Model
  nameWithType: PCConfigurator.Model
  fullName: PCConfigurator.Model
  spec.csharp:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
  spec.vb:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
