### YamlMime:ManagedReference
items:
- uid: PCConfigurator.View.AddComponents
  commentId: N:PCConfigurator.View.AddComponents
  id: PCConfigurator.View.AddComponents
  children:
  - PCConfigurator.View.AddComponents.M2InterfaceUserControl
  - PCConfigurator.View.AddComponents.M2SizeUserControl
  - PCConfigurator.View.AddComponents.M2SlotUserControl
  - PCConfigurator.View.AddComponents.NewCoolerWindow
  - PCConfigurator.View.AddComponents.NewCpuWindow
  - PCConfigurator.View.AddComponents.NewGpuWindow
  - PCConfigurator.View.AddComponents.NewHddWindow
  - PCConfigurator.View.AddComponents.NewM2SsdWindow
  - PCConfigurator.View.AddComponents.NewMotherboardWindow
  - PCConfigurator.View.AddComponents.NewPowerSupplyWindow
  - PCConfigurator.View.AddComponents.NewRamWindow
  - PCConfigurator.View.AddComponents.NewSocketWindow
  - PCConfigurator.View.AddComponents.NewSsdWindow
  langs:
  - csharp
  - vb
  name: PCConfigurator.View.AddComponents
  nameWithType: PCConfigurator.View.AddComponents
  fullName: PCConfigurator.View.AddComponents
  type: Namespace
  assemblies:
  - PCConfigurator
references:
- uid: PCConfigurator.View.AddComponents.M2InterfaceUserControl
  commentId: T:PCConfigurator.View.AddComponents.M2InterfaceUserControl
  href: PCConfigurator.View.AddComponents.M2InterfaceUserControl.html
  name: M2InterfaceUserControl
  nameWithType: M2InterfaceUserControl
  fullName: PCConfigurator.View.AddComponents.M2InterfaceUserControl
- uid: PCConfigurator.View.AddComponents.M2SizeUserControl
  commentId: T:PCConfigurator.View.AddComponents.M2SizeUserControl
  href: PCConfigurator.View.AddComponents.M2SizeUserControl.html
  name: M2SizeUserControl
  nameWithType: M2SizeUserControl
  fullName: PCConfigurator.View.AddComponents.M2SizeUserControl
- uid: PCConfigurator.View.AddComponents.M2SlotUserControl
  commentId: T:PCConfigurator.View.AddComponents.M2SlotUserControl
  href: PCConfigurator.View.AddComponents.M2SlotUserControl.html
  name: M2SlotUserControl
  nameWithType: M2SlotUserControl
  fullName: PCConfigurator.View.AddComponents.M2SlotUserControl
- uid: PCConfigurator.View.AddComponents.NewCoolerWindow
  commentId: T:PCConfigurator.View.AddComponents.NewCoolerWindow
  href: PCConfigurator.View.AddComponents.NewCoolerWindow.html
  name: NewCoolerWindow
  nameWithType: NewCoolerWindow
  fullName: PCConfigurator.View.AddComponents.NewCoolerWindow
- uid: PCConfigurator.View.AddComponents.NewCpuWindow
  commentId: T:PCConfigurator.View.AddComponents.NewCpuWindow
  href: PCConfigurator.View.AddComponents.NewCpuWindow.html
  name: NewCpuWindow
  nameWithType: NewCpuWindow
  fullName: PCConfigurator.View.AddComponents.NewCpuWindow
- uid: PCConfigurator.View.AddComponents.NewGpuWindow
  commentId: T:PCConfigurator.View.AddComponents.NewGpuWindow
  href: PCConfigurator.View.AddComponents.NewGpuWindow.html
  name: NewGpuWindow
  nameWithType: NewGpuWindow
  fullName: PCConfigurator.View.AddComponents.NewGpuWindow
- uid: PCConfigurator.View.AddComponents.NewHddWindow
  commentId: T:PCConfigurator.View.AddComponents.NewHddWindow
  href: PCConfigurator.View.AddComponents.NewHddWindow.html
  name: NewHddWindow
  nameWithType: NewHddWindow
  fullName: PCConfigurator.View.AddComponents.NewHddWindow
- uid: PCConfigurator.View.AddComponents.NewM2SsdWindow
  commentId: T:PCConfigurator.View.AddComponents.NewM2SsdWindow
  href: PCConfigurator.View.AddComponents.NewM2SsdWindow.html
  name: NewM2SsdWindow
  nameWithType: NewM2SsdWindow
  fullName: PCConfigurator.View.AddComponents.NewM2SsdWindow
- uid: PCConfigurator.View.AddComponents.NewMotherboardWindow
  commentId: T:PCConfigurator.View.AddComponents.NewMotherboardWindow
  href: PCConfigurator.View.AddComponents.NewMotherboardWindow.html
  name: NewMotherboardWindow
  nameWithType: NewMotherboardWindow
  fullName: PCConfigurator.View.AddComponents.NewMotherboardWindow
- uid: PCConfigurator.View.AddComponents.NewPowerSupplyWindow
  commentId: T:PCConfigurator.View.AddComponents.NewPowerSupplyWindow
  href: PCConfigurator.View.AddComponents.NewPowerSupplyWindow.html
  name: NewPowerSupplyWindow
  nameWithType: NewPowerSupplyWindow
  fullName: PCConfigurator.View.AddComponents.NewPowerSupplyWindow
- uid: PCConfigurator.View.AddComponents.NewRamWindow
  commentId: T:PCConfigurator.View.AddComponents.NewRamWindow
  href: PCConfigurator.View.AddComponents.NewRamWindow.html
  name: NewRamWindow
  nameWithType: NewRamWindow
  fullName: PCConfigurator.View.AddComponents.NewRamWindow
- uid: PCConfigurator.View.AddComponents.NewSocketWindow
  commentId: T:PCConfigurator.View.AddComponents.NewSocketWindow
  href: PCConfigurator.View.AddComponents.NewSocketWindow.html
  name: NewSocketWindow
  nameWithType: NewSocketWindow
  fullName: PCConfigurator.View.AddComponents.NewSocketWindow
- uid: PCConfigurator.View.AddComponents.NewSsdWindow
  commentId: T:PCConfigurator.View.AddComponents.NewSsdWindow
  href: PCConfigurator.View.AddComponents.NewSsdWindow.html
  name: NewSsdWindow
  nameWithType: NewSsdWindow
  fullName: PCConfigurator.View.AddComponents.NewSsdWindow
