### YamlMime:ManagedReference
items:
- uid: PCConfigurator.Model.Components.FlagsExtension
  commentId: T:PCConfigurator.Model.Components.FlagsExtension
  id: FlagsExtension
  parent: PCConfigurator.Model.Components
  children:
  - PCConfigurator.Model.Components.FlagsExtension.SetInterface(PCConfigurator.Model.Components.M2.M2Interface@,PCConfigurator.Model.Components.M2.M2Interface,System.Boolean)
  - PCConfigurator.Model.Components.FlagsExtension.SetRamType(PCConfigurator.Model.Components.RamType@,PCConfigurator.Model.Components.RamType,System.Boolean)
  - PCConfigurator.Model.Components.FlagsExtension.SetSize(PCConfigurator.Model.Components.M2.M2Size@,PCConfigurator.Model.Components.M2.M2Size,System.Boolean)
  langs:
  - csharp
  - vb
  name: FlagsExtension
  nameWithType: FlagsExtension
  fullName: PCConfigurator.Model.Components.FlagsExtension
  type: Class
  source:
    remote:
      path: PCConfigurator/Model/Components/FlagsExtension.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: FlagsExtension
    path: ../PCConfigurator/Model/Components/FlagsExtension.cs
    startLine: 4
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Model.Components
  syntax:
    content: public static class FlagsExtension
    content.vb: Public Module FlagsExtension
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: PCConfigurator.Model.Components.FlagsExtension.SetInterface(PCConfigurator.Model.Components.M2.M2Interface@,PCConfigurator.Model.Components.M2.M2Interface,System.Boolean)
  commentId: M:PCConfigurator.Model.Components.FlagsExtension.SetInterface(PCConfigurator.Model.Components.M2.M2Interface@,PCConfigurator.Model.Components.M2.M2Interface,System.Boolean)
  id: SetInterface(PCConfigurator.Model.Components.M2.M2Interface@,PCConfigurator.Model.Components.M2.M2Interface,System.Boolean)
  isExtensionMethod: true
  parent: PCConfigurator.Model.Components.FlagsExtension
  langs:
  - csharp
  - vb
  name: SetInterface(ref M2Interface, M2Interface, bool)
  nameWithType: FlagsExtension.SetInterface(ref M2Interface, M2Interface, bool)
  fullName: PCConfigurator.Model.Components.FlagsExtension.SetInterface(ref PCConfigurator.Model.Components.M2.M2Interface, PCConfigurator.Model.Components.M2.M2Interface, bool)
  type: Method
  source:
    remote:
      path: PCConfigurator/Model/Components/FlagsExtension.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: SetInterface
    path: ../PCConfigurator/Model/Components/FlagsExtension.cs
    startLine: 6
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Model.Components
  syntax:
    content: public static void SetInterface(this ref M2Interface self, M2Interface m2Interface, bool value)
    parameters:
    - id: self
      type: PCConfigurator.Model.Components.M2.M2Interface
    - id: m2Interface
      type: PCConfigurator.Model.Components.M2.M2Interface
    - id: value
      type: System.Boolean
    content.vb: Public Shared Sub SetInterface(self As M2Interface, m2Interface As M2Interface, value As Boolean)
  overload: PCConfigurator.Model.Components.FlagsExtension.SetInterface*
  nameWithType.vb: FlagsExtension.SetInterface(M2Interface, M2Interface, Boolean)
  fullName.vb: PCConfigurator.Model.Components.FlagsExtension.SetInterface(PCConfigurator.Model.Components.M2.M2Interface, PCConfigurator.Model.Components.M2.M2Interface, Boolean)
  name.vb: SetInterface(M2Interface, M2Interface, Boolean)
- uid: PCConfigurator.Model.Components.FlagsExtension.SetSize(PCConfigurator.Model.Components.M2.M2Size@,PCConfigurator.Model.Components.M2.M2Size,System.Boolean)
  commentId: M:PCConfigurator.Model.Components.FlagsExtension.SetSize(PCConfigurator.Model.Components.M2.M2Size@,PCConfigurator.Model.Components.M2.M2Size,System.Boolean)
  id: SetSize(PCConfigurator.Model.Components.M2.M2Size@,PCConfigurator.Model.Components.M2.M2Size,System.Boolean)
  isExtensionMethod: true
  parent: PCConfigurator.Model.Components.FlagsExtension
  langs:
  - csharp
  - vb
  name: SetSize(ref M2Size, M2Size, bool)
  nameWithType: FlagsExtension.SetSize(ref M2Size, M2Size, bool)
  fullName: PCConfigurator.Model.Components.FlagsExtension.SetSize(ref PCConfigurator.Model.Components.M2.M2Size, PCConfigurator.Model.Components.M2.M2Size, bool)
  type: Method
  source:
    remote:
      path: PCConfigurator/Model/Components/FlagsExtension.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: SetSize
    path: ../PCConfigurator/Model/Components/FlagsExtension.cs
    startLine: 14
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Model.Components
  syntax:
    content: public static void SetSize(this ref M2Size self, M2Size size, bool value)
    parameters:
    - id: self
      type: PCConfigurator.Model.Components.M2.M2Size
    - id: size
      type: PCConfigurator.Model.Components.M2.M2Size
    - id: value
      type: System.Boolean
    content.vb: Public Shared Sub SetSize(self As M2Size, size As M2Size, value As Boolean)
  overload: PCConfigurator.Model.Components.FlagsExtension.SetSize*
  nameWithType.vb: FlagsExtension.SetSize(M2Size, M2Size, Boolean)
  fullName.vb: PCConfigurator.Model.Components.FlagsExtension.SetSize(PCConfigurator.Model.Components.M2.M2Size, PCConfigurator.Model.Components.M2.M2Size, Boolean)
  name.vb: SetSize(M2Size, M2Size, Boolean)
- uid: PCConfigurator.Model.Components.FlagsExtension.SetRamType(PCConfigurator.Model.Components.RamType@,PCConfigurator.Model.Components.RamType,System.Boolean)
  commentId: M:PCConfigurator.Model.Components.FlagsExtension.SetRamType(PCConfigurator.Model.Components.RamType@,PCConfigurator.Model.Components.RamType,System.Boolean)
  id: SetRamType(PCConfigurator.Model.Components.RamType@,PCConfigurator.Model.Components.RamType,System.Boolean)
  isExtensionMethod: true
  parent: PCConfigurator.Model.Components.FlagsExtension
  langs:
  - csharp
  - vb
  name: SetRamType(ref RamType, RamType, bool)
  nameWithType: FlagsExtension.SetRamType(ref RamType, RamType, bool)
  fullName: PCConfigurator.Model.Components.FlagsExtension.SetRamType(ref PCConfigurator.Model.Components.RamType, PCConfigurator.Model.Components.RamType, bool)
  type: Method
  source:
    remote:
      path: PCConfigurator/Model/Components/FlagsExtension.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: SetRamType
    path: ../PCConfigurator/Model/Components/FlagsExtension.cs
    startLine: 22
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Model.Components
  syntax:
    content: public static void SetRamType(this ref RamType self, RamType type, bool value)
    parameters:
    - id: self
      type: PCConfigurator.Model.Components.RamType
    - id: type
      type: PCConfigurator.Model.Components.RamType
    - id: value
      type: System.Boolean
    content.vb: Public Shared Sub SetRamType(self As RamType, type As RamType, value As Boolean)
  overload: PCConfigurator.Model.Components.FlagsExtension.SetRamType*
  nameWithType.vb: FlagsExtension.SetRamType(RamType, RamType, Boolean)
  fullName.vb: PCConfigurator.Model.Components.FlagsExtension.SetRamType(PCConfigurator.Model.Components.RamType, PCConfigurator.Model.Components.RamType, Boolean)
  name.vb: SetRamType(RamType, RamType, Boolean)
references:
- uid: PCConfigurator.Model.Components
  commentId: N:PCConfigurator.Model.Components
  href: PCConfigurator.html
  name: PCConfigurator.Model.Components
  nameWithType: PCConfigurator.Model.Components
  fullName: PCConfigurator.Model.Components
  spec.csharp:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
  - name: .
  - uid: PCConfigurator.Model.Components
    name: Components
    href: PCConfigurator.Model.Components.html
  spec.vb:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
  - name: .
  - uid: PCConfigurator.Model.Components
    name: Components
    href: PCConfigurator.Model.Components.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: PCConfigurator.Model.Components.FlagsExtension.SetInterface*
  commentId: Overload:PCConfigurator.Model.Components.FlagsExtension.SetInterface
  href: PCConfigurator.Model.Components.FlagsExtension.html#PCConfigurator_Model_Components_FlagsExtension_SetInterface_PCConfigurator_Model_Components_M2_M2Interface__PCConfigurator_Model_Components_M2_M2Interface_System_Boolean_
  name: SetInterface
  nameWithType: FlagsExtension.SetInterface
  fullName: PCConfigurator.Model.Components.FlagsExtension.SetInterface
- uid: PCConfigurator.Model.Components.M2.M2Interface
  commentId: T:PCConfigurator.Model.Components.M2.M2Interface
  parent: PCConfigurator.Model.Components.M2
  href: PCConfigurator.Model.Components.M2.M2Interface.html
  name: M2Interface
  nameWithType: M2Interface
  fullName: PCConfigurator.Model.Components.M2.M2Interface
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: PCConfigurator.Model.Components.M2
  commentId: N:PCConfigurator.Model.Components.M2
  href: PCConfigurator.html
  name: PCConfigurator.Model.Components.M2
  nameWithType: PCConfigurator.Model.Components.M2
  fullName: PCConfigurator.Model.Components.M2
  spec.csharp:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
  - name: .
  - uid: PCConfigurator.Model.Components
    name: Components
    href: PCConfigurator.Model.Components.html
  - name: .
  - uid: PCConfigurator.Model.Components.M2
    name: M2
    href: PCConfigurator.Model.Components.M2.html
  spec.vb:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
  - name: .
  - uid: PCConfigurator.Model.Components
    name: Components
    href: PCConfigurator.Model.Components.html
  - name: .
  - uid: PCConfigurator.Model.Components.M2
    name: M2
    href: PCConfigurator.Model.Components.M2.html
- uid: PCConfigurator.Model.Components.FlagsExtension.SetSize*
  commentId: Overload:PCConfigurator.Model.Components.FlagsExtension.SetSize
  href: PCConfigurator.Model.Components.FlagsExtension.html#PCConfigurator_Model_Components_FlagsExtension_SetSize_PCConfigurator_Model_Components_M2_M2Size__PCConfigurator_Model_Components_M2_M2Size_System_Boolean_
  name: SetSize
  nameWithType: FlagsExtension.SetSize
  fullName: PCConfigurator.Model.Components.FlagsExtension.SetSize
- uid: PCConfigurator.Model.Components.M2.M2Size
  commentId: T:PCConfigurator.Model.Components.M2.M2Size
  parent: PCConfigurator.Model.Components.M2
  href: PCConfigurator.Model.Components.M2.M2Size.html
  name: M2Size
  nameWithType: M2Size
  fullName: PCConfigurator.Model.Components.M2.M2Size
- uid: PCConfigurator.Model.Components.FlagsExtension.SetRamType*
  commentId: Overload:PCConfigurator.Model.Components.FlagsExtension.SetRamType
  href: PCConfigurator.Model.Components.FlagsExtension.html#PCConfigurator_Model_Components_FlagsExtension_SetRamType_PCConfigurator_Model_Components_RamType__PCConfigurator_Model_Components_RamType_System_Boolean_
  name: SetRamType
  nameWithType: FlagsExtension.SetRamType
  fullName: PCConfigurator.Model.Components.FlagsExtension.SetRamType
- uid: PCConfigurator.Model.Components.RamType
  commentId: T:PCConfigurator.Model.Components.RamType
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.RamType.html
  name: RamType
  nameWithType: RamType
  fullName: PCConfigurator.Model.Components.RamType
