### YamlMime:ManagedReference
items:
- uid: PCConfigurator.Model.Components.ConfigurationRam
  commentId: T:PCConfigurator.Model.Components.ConfigurationRam
  id: ConfigurationRam
  parent: PCConfigurator.Model.Components
  children:
  - PCConfigurator.Model.Components.ConfigurationRam.Configuration
  - PCConfigurator.Model.Components.ConfigurationRam.ConfigurationId
  - PCConfigurator.Model.Components.ConfigurationRam.ConfigurationRamId
  - PCConfigurator.Model.Components.ConfigurationRam.Ram
  - PCConfigurator.Model.Components.ConfigurationRam.RamId
  langs:
  - csharp
  - vb
  name: ConfigurationRam
  nameWithType: ConfigurationRam
  fullName: PCConfigurator.Model.Components.ConfigurationRam
  type: Class
  source:
    remote:
      path: PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: ConfigurationRam
    path: ../PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
    startLine: 2
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Model.Components
  syntax:
    content: public class ConfigurationRam
    content.vb: Public Class ConfigurationRam
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: PCConfigurator.Model.Components.ConfigurationRam.ConfigurationRamId
  commentId: P:PCConfigurator.Model.Components.ConfigurationRam.ConfigurationRamId
  id: ConfigurationRamId
  parent: PCConfigurator.Model.Components.ConfigurationRam
  langs:
  - csharp
  - vb
  name: ConfigurationRamId
  nameWithType: ConfigurationRam.ConfigurationRamId
  fullName: PCConfigurator.Model.Components.ConfigurationRam.ConfigurationRamId
  type: Property
  source:
    remote:
      path: PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: ConfigurationRamId
    path: ../PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
    startLine: 4
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Model.Components
  syntax:
    content: public int ConfigurationRamId { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property ConfigurationRamId As Integer
  overload: PCConfigurator.Model.Components.ConfigurationRam.ConfigurationRamId*
- uid: PCConfigurator.Model.Components.ConfigurationRam.ConfigurationId
  commentId: P:PCConfigurator.Model.Components.ConfigurationRam.ConfigurationId
  id: ConfigurationId
  parent: PCConfigurator.Model.Components.ConfigurationRam
  langs:
  - csharp
  - vb
  name: ConfigurationId
  nameWithType: ConfigurationRam.ConfigurationId
  fullName: PCConfigurator.Model.Components.ConfigurationRam.ConfigurationId
  type: Property
  source:
    remote:
      path: PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: ConfigurationId
    path: ../PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
    startLine: 6
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Model.Components
  syntax:
    content: public int ConfigurationId { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property ConfigurationId As Integer
  overload: PCConfigurator.Model.Components.ConfigurationRam.ConfigurationId*
- uid: PCConfigurator.Model.Components.ConfigurationRam.Configuration
  commentId: P:PCConfigurator.Model.Components.ConfigurationRam.Configuration
  id: Configuration
  parent: PCConfigurator.Model.Components.ConfigurationRam
  langs:
  - csharp
  - vb
  name: Configuration
  nameWithType: ConfigurationRam.Configuration
  fullName: PCConfigurator.Model.Components.ConfigurationRam.Configuration
  type: Property
  source:
    remote:
      path: PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: Configuration
    path: ../PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
    startLine: 7
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Model.Components
  syntax:
    content: public virtual Configuration Configuration { get; set; }
    parameters: []
    return:
      type: PCConfigurator.Model.Components.Configuration
    content.vb: Public Overridable Property Configuration As Configuration
  overload: PCConfigurator.Model.Components.ConfigurationRam.Configuration*
- uid: PCConfigurator.Model.Components.ConfigurationRam.RamId
  commentId: P:PCConfigurator.Model.Components.ConfigurationRam.RamId
  id: RamId
  parent: PCConfigurator.Model.Components.ConfigurationRam
  langs:
  - csharp
  - vb
  name: RamId
  nameWithType: ConfigurationRam.RamId
  fullName: PCConfigurator.Model.Components.ConfigurationRam.RamId
  type: Property
  source:
    remote:
      path: PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: RamId
    path: ../PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
    startLine: 9
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Model.Components
  syntax:
    content: public int RamId { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property RamId As Integer
  overload: PCConfigurator.Model.Components.ConfigurationRam.RamId*
- uid: PCConfigurator.Model.Components.ConfigurationRam.Ram
  commentId: P:PCConfigurator.Model.Components.ConfigurationRam.Ram
  id: Ram
  parent: PCConfigurator.Model.Components.ConfigurationRam
  langs:
  - csharp
  - vb
  name: Ram
  nameWithType: ConfigurationRam.Ram
  fullName: PCConfigurator.Model.Components.ConfigurationRam.Ram
  type: Property
  source:
    remote:
      path: PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
      branch: master
      repo: https://github.com/son1k9/PCConfigurator.git
    id: Ram
    path: ../PCConfigurator/Model/Components/ManyToMany/ConfigurationRam.cs
    startLine: 10
  assemblies:
  - PCConfigurator
  namespace: PCConfigurator.Model.Components
  syntax:
    content: public virtual Ram Ram { get; set; }
    parameters: []
    return:
      type: PCConfigurator.Model.Components.Ram
    content.vb: Public Overridable Property Ram As Ram
  overload: PCConfigurator.Model.Components.ConfigurationRam.Ram*
references:
- uid: PCConfigurator.Model.Components
  commentId: N:PCConfigurator.Model.Components
  href: PCConfigurator.html
  name: PCConfigurator.Model.Components
  nameWithType: PCConfigurator.Model.Components
  fullName: PCConfigurator.Model.Components
  spec.csharp:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
  - name: .
  - uid: PCConfigurator.Model.Components
    name: Components
    href: PCConfigurator.Model.Components.html
  spec.vb:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
  - name: .
  - uid: PCConfigurator.Model.Components
    name: Components
    href: PCConfigurator.Model.Components.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: PCConfigurator.Model.Components.ConfigurationRam.ConfigurationRamId*
  commentId: Overload:PCConfigurator.Model.Components.ConfigurationRam.ConfigurationRamId
  href: PCConfigurator.Model.Components.ConfigurationRam.html#PCConfigurator_Model_Components_ConfigurationRam_ConfigurationRamId
  name: ConfigurationRamId
  nameWithType: ConfigurationRam.ConfigurationRamId
  fullName: PCConfigurator.Model.Components.ConfigurationRam.ConfigurationRamId
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: PCConfigurator.Model.Components.ConfigurationRam.ConfigurationId*
  commentId: Overload:PCConfigurator.Model.Components.ConfigurationRam.ConfigurationId
  href: PCConfigurator.Model.Components.ConfigurationRam.html#PCConfigurator_Model_Components_ConfigurationRam_ConfigurationId
  name: ConfigurationId
  nameWithType: ConfigurationRam.ConfigurationId
  fullName: PCConfigurator.Model.Components.ConfigurationRam.ConfigurationId
- uid: PCConfigurator.Model.Components.ConfigurationRam.Configuration*
  commentId: Overload:PCConfigurator.Model.Components.ConfigurationRam.Configuration
  href: PCConfigurator.Model.Components.ConfigurationRam.html#PCConfigurator_Model_Components_ConfigurationRam_Configuration
  name: Configuration
  nameWithType: ConfigurationRam.Configuration
  fullName: PCConfigurator.Model.Components.ConfigurationRam.Configuration
- uid: PCConfigurator.Model.Components.Configuration
  commentId: T:PCConfigurator.Model.Components.Configuration
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Configuration.html
  name: Configuration
  nameWithType: Configuration
  fullName: PCConfigurator.Model.Components.Configuration
- uid: PCConfigurator.Model.Components.ConfigurationRam.RamId*
  commentId: Overload:PCConfigurator.Model.Components.ConfigurationRam.RamId
  href: PCConfigurator.Model.Components.ConfigurationRam.html#PCConfigurator_Model_Components_ConfigurationRam_RamId
  name: RamId
  nameWithType: ConfigurationRam.RamId
  fullName: PCConfigurator.Model.Components.ConfigurationRam.RamId
- uid: PCConfigurator.Model.Components.ConfigurationRam.Ram*
  commentId: Overload:PCConfigurator.Model.Components.ConfigurationRam.Ram
  href: PCConfigurator.Model.Components.ConfigurationRam.html#PCConfigurator_Model_Components_ConfigurationRam_Ram
  name: Ram
  nameWithType: ConfigurationRam.Ram
  fullName: PCConfigurator.Model.Components.ConfigurationRam.Ram
- uid: PCConfigurator.Model.Components.Ram
  commentId: T:PCConfigurator.Model.Components.Ram
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Ram.html
  name: Ram
  nameWithType: Ram
  fullName: PCConfigurator.Model.Components.Ram
