### YamlMime:ManagedReference
items:
- uid: PCConfigurator.Model.Components
  commentId: N:PCConfigurator.Model.Components
  id: PCConfigurator.Model.Components
  children:
  - PCConfigurator.Model.Components.Chipset
  - PCConfigurator.Model.Components.Component
  - PCConfigurator.Model.Components.Configuration
  - PCConfigurator.Model.Components.ConfigurationGpu
  - PCConfigurator.Model.Components.ConfigurationHdd
  - PCConfigurator.Model.Components.ConfigurationM2Ssd
  - PCConfigurator.Model.Components.ConfigurationRam
  - PCConfigurator.Model.Components.ConfigurationSsd
  - PCConfigurator.Model.Components.Cooler
  - PCConfigurator.Model.Components.Cpu
  - PCConfigurator.Model.Components.FlagsExtension
  - PCConfigurator.Model.Components.Gpu
  - PCConfigurator.Model.Components.Hdd
  - PCConfigurator.Model.Components.M2Slot
  - PCConfigurator.Model.Components.M2Ssd
  - PCConfigurator.Model.Components.Motherboard
  - PCConfigurator.Model.Components.NandType
  - PCConfigurator.Model.Components.PowerSupply
  - PCConfigurator.Model.Components.Ram
  - PCConfigurator.Model.Components.RamType
  - PCConfigurator.Model.Components.Socket
  - PCConfigurator.Model.Components.Ssd
  langs:
  - csharp
  - vb
  name: PCConfigurator.Model.Components
  nameWithType: PCConfigurator.Model.Components
  fullName: PCConfigurator.Model.Components
  type: Namespace
  assemblies:
  - PCConfigurator
references:
- uid: PCConfigurator.Model.Components.Chipset
  commentId: T:PCConfigurator.Model.Components.Chipset
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Chipset.html
  name: Chipset
  nameWithType: Chipset
  fullName: PCConfigurator.Model.Components.Chipset
- uid: PCConfigurator.Model.Components.Component
  commentId: T:PCConfigurator.Model.Components.Component
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Component.html
  name: Component
  nameWithType: Component
  fullName: PCConfigurator.Model.Components.Component
- uid: PCConfigurator.Model.Components.Configuration
  commentId: T:PCConfigurator.Model.Components.Configuration
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Configuration.html
  name: Configuration
  nameWithType: Configuration
  fullName: PCConfigurator.Model.Components.Configuration
- uid: PCConfigurator.Model.Components.Cooler
  commentId: T:PCConfigurator.Model.Components.Cooler
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Cooler.html
  name: Cooler
  nameWithType: Cooler
  fullName: PCConfigurator.Model.Components.Cooler
- uid: PCConfigurator.Model.Components.Cpu
  commentId: T:PCConfigurator.Model.Components.Cpu
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Cpu.html
  name: Cpu
  nameWithType: Cpu
  fullName: PCConfigurator.Model.Components.Cpu
- uid: PCConfigurator.Model.Components.FlagsExtension
  commentId: T:PCConfigurator.Model.Components.FlagsExtension
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.FlagsExtension.html
  name: FlagsExtension
  nameWithType: FlagsExtension
  fullName: PCConfigurator.Model.Components.FlagsExtension
- uid: PCConfigurator.Model.Components.Gpu
  commentId: T:PCConfigurator.Model.Components.Gpu
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Gpu.html
  name: Gpu
  nameWithType: Gpu
  fullName: PCConfigurator.Model.Components.Gpu
- uid: PCConfigurator.Model.Components.Hdd
  commentId: T:PCConfigurator.Model.Components.Hdd
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Hdd.html
  name: Hdd
  nameWithType: Hdd
  fullName: PCConfigurator.Model.Components.Hdd
- uid: PCConfigurator.Model.Components.M2Slot
  commentId: T:PCConfigurator.Model.Components.M2Slot
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.M2Slot.html
  name: M2Slot
  nameWithType: M2Slot
  fullName: PCConfigurator.Model.Components.M2Slot
- uid: PCConfigurator.Model.Components.M2Ssd
  commentId: T:PCConfigurator.Model.Components.M2Ssd
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.M2Ssd.html
  name: M2Ssd
  nameWithType: M2Ssd
  fullName: PCConfigurator.Model.Components.M2Ssd
- uid: PCConfigurator.Model.Components.ConfigurationGpu
  commentId: T:PCConfigurator.Model.Components.ConfigurationGpu
  href: PCConfigurator.Model.Components.ConfigurationGpu.html
  name: ConfigurationGpu
  nameWithType: ConfigurationGpu
  fullName: PCConfigurator.Model.Components.ConfigurationGpu
- uid: PCConfigurator.Model.Components.ConfigurationHdd
  commentId: T:PCConfigurator.Model.Components.ConfigurationHdd
  href: PCConfigurator.Model.Components.ConfigurationHdd.html
  name: ConfigurationHdd
  nameWithType: ConfigurationHdd
  fullName: PCConfigurator.Model.Components.ConfigurationHdd
- uid: PCConfigurator.Model.Components.ConfigurationM2Ssd
  commentId: T:PCConfigurator.Model.Components.ConfigurationM2Ssd
  href: PCConfigurator.Model.Components.ConfigurationM2Ssd.html
  name: ConfigurationM2Ssd
  nameWithType: ConfigurationM2Ssd
  fullName: PCConfigurator.Model.Components.ConfigurationM2Ssd
- uid: PCConfigurator.Model.Components.ConfigurationRam
  commentId: T:PCConfigurator.Model.Components.ConfigurationRam
  href: PCConfigurator.Model.Components.ConfigurationRam.html
  name: ConfigurationRam
  nameWithType: ConfigurationRam
  fullName: PCConfigurator.Model.Components.ConfigurationRam
- uid: PCConfigurator.Model.Components.ConfigurationSsd
  commentId: T:PCConfigurator.Model.Components.ConfigurationSsd
  href: PCConfigurator.Model.Components.ConfigurationSsd.html
  name: ConfigurationSsd
  nameWithType: ConfigurationSsd
  fullName: PCConfigurator.Model.Components.ConfigurationSsd
- uid: PCConfigurator.Model.Components.Motherboard
  commentId: T:PCConfigurator.Model.Components.Motherboard
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Motherboard.html
  name: Motherboard
  nameWithType: Motherboard
  fullName: PCConfigurator.Model.Components.Motherboard
- uid: PCConfigurator.Model.Components.NandType
  commentId: T:PCConfigurator.Model.Components.NandType
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.NandType.html
  name: NandType
  nameWithType: NandType
  fullName: PCConfigurator.Model.Components.NandType
- uid: PCConfigurator.Model.Components.PowerSupply
  commentId: T:PCConfigurator.Model.Components.PowerSupply
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.PowerSupply.html
  name: PowerSupply
  nameWithType: PowerSupply
  fullName: PCConfigurator.Model.Components.PowerSupply
- uid: PCConfigurator.Model.Components.Ram
  commentId: T:PCConfigurator.Model.Components.Ram
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Ram.html
  name: Ram
  nameWithType: Ram
  fullName: PCConfigurator.Model.Components.Ram
- uid: PCConfigurator.Model.Components.RamType
  commentId: T:PCConfigurator.Model.Components.RamType
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.RamType.html
  name: RamType
  nameWithType: RamType
  fullName: PCConfigurator.Model.Components.RamType
- uid: PCConfigurator.Model.Components.Socket
  commentId: T:PCConfigurator.Model.Components.Socket
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Socket.html
  name: Socket
  nameWithType: Socket
  fullName: PCConfigurator.Model.Components.Socket
- uid: PCConfigurator.Model.Components.Ssd
  commentId: T:PCConfigurator.Model.Components.Ssd
  parent: PCConfigurator.Model.Components
  href: PCConfigurator.Model.Components.Ssd.html
  name: Ssd
  nameWithType: Ssd
  fullName: PCConfigurator.Model.Components.Ssd
- uid: PCConfigurator.Model.Components
  commentId: N:PCConfigurator.Model.Components
  href: PCConfigurator.html
  name: PCConfigurator.Model.Components
  nameWithType: PCConfigurator.Model.Components
  fullName: PCConfigurator.Model.Components
  spec.csharp:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
  - name: .
  - uid: PCConfigurator.Model.Components
    name: Components
    href: PCConfigurator.Model.Components.html
  spec.vb:
  - uid: PCConfigurator
    name: PCConfigurator
    href: PCConfigurator.html
  - name: .
  - uid: PCConfigurator.Model
    name: Model
    href: PCConfigurator.Model.html
  - name: .
  - uid: PCConfigurator.Model.Components
    name: Components
    href: PCConfigurator.Model.Components.html
