### YamlMime:ManagedReference
items:
- uid: PCConfigurator.View.ComponentsUserControls
  commentId: N:PCConfigurator.View.ComponentsUserControls
  id: PCConfigurator.View.ComponentsUserControls
  children:
  - PCConfigurator.View.ComponentsUserControls.CoolerUserControl
  - PCConfigurator.View.ComponentsUserControls.CpuUserControl
  - PCConfigurator.View.ComponentsUserControls.GpuUserControl
  - PCConfigurator.View.ComponentsUserControls.HddUserControl
  - PCConfigurator.View.ComponentsUserControls.M2SsdUserControl
  - PCConfigurator.View.ComponentsUserControls.MotherboardUserControl
  - PCConfigurator.View.ComponentsUserControls.PowerSupplyUserControl
  - PCConfigurator.View.ComponentsUserControls.RamUserControl
  - PCConfigurator.View.ComponentsUserControls.SocketUserControl
  - PCConfigurator.View.ComponentsUserControls.SsdUserControl
  langs:
  - csharp
  - vb
  name: PCConfigurator.View.ComponentsUserControls
  nameWithType: PCConfigurator.View.ComponentsUserControls
  fullName: PCConfigurator.View.ComponentsUserControls
  type: Namespace
  assemblies:
  - PCConfigurator
references:
- uid: PCConfigurator.View.ComponentsUserControls.CoolerUserControl
  commentId: T:PCConfigurator.View.ComponentsUserControls.CoolerUserControl
  href: PCConfigurator.View.ComponentsUserControls.CoolerUserControl.html
  name: CoolerUserControl
  nameWithType: CoolerUserControl
  fullName: PCConfigurator.View.ComponentsUserControls.CoolerUserControl
- uid: PCConfigurator.View.ComponentsUserControls.CpuUserControl
  commentId: T:PCConfigurator.View.ComponentsUserControls.CpuUserControl
  href: PCConfigurator.View.ComponentsUserControls.CpuUserControl.html
  name: CpuUserControl
  nameWithType: CpuUserControl
  fullName: PCConfigurator.View.ComponentsUserControls.CpuUserControl
- uid: PCConfigurator.View.ComponentsUserControls.GpuUserControl
  commentId: T:PCConfigurator.View.ComponentsUserControls.GpuUserControl
  href: PCConfigurator.View.ComponentsUserControls.GpuUserControl.html
  name: GpuUserControl
  nameWithType: GpuUserControl
  fullName: PCConfigurator.View.ComponentsUserControls.GpuUserControl
- uid: PCConfigurator.View.ComponentsUserControls.HddUserControl
  commentId: T:PCConfigurator.View.ComponentsUserControls.HddUserControl
  href: PCConfigurator.View.ComponentsUserControls.HddUserControl.html
  name: HddUserControl
  nameWithType: HddUserControl
  fullName: PCConfigurator.View.ComponentsUserControls.HddUserControl
- uid: PCConfigurator.View.ComponentsUserControls.M2SsdUserControl
  commentId: T:PCConfigurator.View.ComponentsUserControls.M2SsdUserControl
  href: PCConfigurator.View.ComponentsUserControls.M2SsdUserControl.html
  name: M2SsdUserControl
  nameWithType: M2SsdUserControl
  fullName: PCConfigurator.View.ComponentsUserControls.M2SsdUserControl
- uid: PCConfigurator.View.ComponentsUserControls.MotherboardUserControl
  commentId: T:PCConfigurator.View.ComponentsUserControls.MotherboardUserControl
  href: PCConfigurator.View.ComponentsUserControls.MotherboardUserControl.html
  name: MotherboardUserControl
  nameWithType: MotherboardUserControl
  fullName: PCConfigurator.View.ComponentsUserControls.MotherboardUserControl
- uid: PCConfigurator.View.ComponentsUserControls.PowerSupplyUserControl
  commentId: T:PCConfigurator.View.ComponentsUserControls.PowerSupplyUserControl
  href: PCConfigurator.View.ComponentsUserControls.PowerSupplyUserControl.html
  name: PowerSupplyUserControl
  nameWithType: PowerSupplyUserControl
  fullName: PCConfigurator.View.ComponentsUserControls.PowerSupplyUserControl
- uid: PCConfigurator.View.ComponentsUserControls.RamUserControl
  commentId: T:PCConfigurator.View.ComponentsUserControls.RamUserControl
  href: PCConfigurator.View.ComponentsUserControls.RamUserControl.html
  name: RamUserControl
  nameWithType: RamUserControl
  fullName: PCConfigurator.View.ComponentsUserControls.RamUserControl
- uid: PCConfigurator.View.ComponentsUserControls.SocketUserControl
  commentId: T:PCConfigurator.View.ComponentsUserControls.SocketUserControl
  href: PCConfigurator.View.ComponentsUserControls.SocketUserControl.html
  name: SocketUserControl
  nameWithType: SocketUserControl
  fullName: PCConfigurator.View.ComponentsUserControls.SocketUserControl
- uid: PCConfigurator.View.ComponentsUserControls.SsdUserControl
  commentId: T:PCConfigurator.View.ComponentsUserControls.SsdUserControl
  href: PCConfigurator.View.ComponentsUserControls.SsdUserControl.html
  name: SsdUserControl
  nameWithType: SsdUserControl
  fullName: PCConfigurator.View.ComponentsUserControls.SsdUserControl
