@startuml activity1
start
:Выбор пользователем таблицы;
while ()
if (Добавление) then (да)
    repeat :Ввод пользователем характеристик;
    backward : Сообщение с указанием характеристик, 
            которые не были указаны;
    repeat while (Все необходимые 
    поля заполнены) is (нет)
    :Добавление комплектующего;
(нет) elseif (Редактирование) then (да)
    repeat :Ввод пользователем характеристик;
    backward :Сообщение с указанием характеристик,
            которые не были указаны;
    repeat while (Все необходимые поля заполнены) is (нет)
    if (Есть сборки, которые станут не совместимыми) then (нет)
        :Редактирование комплектующего;
    else (да)
        :Вывод сообщения о том, что некоторые 
                сборки станут несовместимы;
    endif
(нет) elseif (Удаление) then (да)
    if (Есть сборки, в которых используется
               это комплектующее) then (нет)
        :Удаление комплектующего;
    else (да)
        :Вывод сообщения о том, что есть сборки, в которых 
        используется данное комплектующее;
    endif
else (нет)
    stop
endif
endwhile
-[hidden]->
@enduml