@startuml a5
:Выбор сборки пользователем;
:Указание пользователем пути;
if (Сборка совместима) then (да)
    :Создать файл с информацией о сборке 
                        по указнному пути;
else (нет)
    :  Вывод сообщения о том, 
    что сборка несовместима;
endif
stop
@enduml