@startuml activity2
if (Импорт) then (да)
    :Указание пользователем пути к файлу;
    :Импорт сборки из файла;
    if (Ошибка во время импорта) then (да)
        :Вывод сообщения об ошибке;
        stop
    endif
else (нет)
    :Создание новой сборки;
    :Ввод пользователем названия сборки;
endif
if (Пользователь сохранил сборку) then (да)
    :Добавление сборки в список сборок;
endif
stop
@enduml