@startuml activity3

:Выбор сборки пользователем;
:Открытие редактора сборок 
    с выбранной сборкой;
:Проверка совместимости сборки 
                и вывод ошибок;
while()
:Добавление и изменение компонентов сборки;
if (Проверить сборку) then (да)
    :Проверка совместимости сборки 
                и вывод ошибок;
(нет) elseif (Сохранить сборку) then (да)
        :Проверка совместимости сборки 
                    и вывод ошибок;
        :Сохранение сборки;
(нет) elseif (Закрыть сборку) then (да)
        :      Вывод сообщения 
        "Сохранить изменения?";
        if (Отмена) then (да)
        else (нет)
            if (Сохранить сборку) then (да)
                :Сохранение сборки;
            else (нет)
            endif
            stop
        endif
else (нет)
endif
endwhile
-[hidden]->

@enduml