@startuml Class diagram ViewModel

interface INotifyPropertyChanged

BaseViewModel ..|> INotifyPropertyChanged
abstract class BaseViewModel{
    + PropertyChanged : PropertyChangedEventHandler?

    # OnPropertyChanged(propertyName:string)
}

@enduml